version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api-db
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PWD:-postgres}
      POSTGRES_DB: ${PG_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

