version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anti-fraud
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
