spring:
  datasource:
    hikari:
      maximum-pool-size: 10
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
---
spring:
  config:
    activate:
      on-profile: "pg"
  datasource:
    url: jdbc:postgresql://localhost:5432/anti-fraud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
db:
  init:
    user-count: 1000
---
spring:
  config:
    activate:
      on-profile: "h2"
  datasource:
    url: jdbc:h2:mem:testdb
    username: local
    password: local
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
