version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PWD:-guest}
    volumes:
      - ./message-broker/rabbitmq/rabbitmq_data:/var/lib/rabbitmq
      - ./message-broker/rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
  postgres:
    image: postgres:latest
    container_name: api-db
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PWD:-postgres}
      POSTGRES_DB: ${PG_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/pgdata:/var/lib/postgresql/data
